# Generated by Django 6.0.6 on 2026-09-24 06:39

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cashier_pin', models.CharField(default='1234', help_text='PIN for cashiers of this branch', max_length=32)),
                ('manager_pin', models.CharField(default='7788', help_text='PIN for manager of this branch', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('failed_pin_attempts', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('locked_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('last_unlocked_at', models.DateTimeField(blank=True, null=True)),
                ('last_unlocked_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_name', models.CharField(default='tv', help_text='Lucide icon name', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(db_index=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('business_name', models.CharField(blank=True, help_text='e.g. Shop at Onitsha', max_length=150, null=True)),
                ('guarantor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('guarantor_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('total_credit_limit', models.DecimalField(decimal_places=2, default=Decimal('500000.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='Matteo Williams Electronics', max_length=200)),
                ('business_tagline', models.CharField(default='Wholesale & Retail Electronics Hub - Onitsha', max_length=300)),
                ('business_phone', models.CharField(default='+234 803 892 4510', max_length=50)),
                ('business_address', models.CharField(default='Onitsha Commercial Center, Anambra State', max_length=300)),
                ('general_password', models.CharField(default='Matteo2025', max_length=128)),
                ('owner_username', models.CharField(default='owner', max_length=100)),
                ('owner_pin', models.CharField(default='0000', max_length=32)),
                ('owner_password', models.CharField(default='Owner@Matteo2025', max_length=128)),
            ],
            options={
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.CharField(choices=[('OWNER', 'Owner'), ('MANAGER', 'Manager'), ('CASHIER', 'Cashier'), ('GATEWAY', 'General Gateway')], max_length=20)),
                ('actor_name', models.CharField(max_length=100)),
                ('action_type', models.CharField(max_length=80)),
                ('details', models.TextField()),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='inventory.branch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('sku', models.CharField(max_length=50, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Naira - Hidden from Cashiers', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Naira - Standard Selling Price', max_digits=12)),
                ('min_selling_price', models.DecimalField(decimal_places=2, help_text='Floor price - Requires manager permission below this', max_digits=12)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('warranty_info', models.CharField(default='1 Year Manufacturer Warranty', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=60, unique=True)),
                ('cashier_name', models.CharField(max_length=100)),
                ('customer_name_snapshot', models.CharField(blank=True, max_length=150, null=True)),
                ('customer_phone_snapshot', models.CharField(blank=True, max_length=50, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_owed', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('payment_status', models.CharField(choices=[('PAID_FULL', 'Paid in Full'), ('PARTIAL_DEBT', 'Split / Partial Debt'), ('FULL_DEBT', '100% Credit / Total Debt')], default='PAID_FULL', max_length=20)),
                ('debt_due_date', models.DateField(blank=True, help_text='Promised debt repayment date', null=True)),
                ('is_manager_approved', models.BooleanField(default=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.branch')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='inventory.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('CASH', 'Cash Payment'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS / Card'), ('DEBT', 'Credit / Debt Owed')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference_note', models.CharField(blank=True, help_text='e.g. OPay transfer ref, Moniepoint terminal slip', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='DebtRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=60, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash Payment'), ('TRANSFER', 'Bank Transfer'), ('POS', 'POS / Card')], default='CASH', max_length=20)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_by', models.CharField(max_length=100)),
                ('received_by_role', models.CharField(default='Cashier', max_length=50)),
                ('reference_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='inventory.customer')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_repayments', to='inventory.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='BranchStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=5)),
                ('last_restocked', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_stocks', to='inventory.product')),
            ],
            options={
                'ordering': ['product__name'],
                'unique_together': {('branch', 'product')},
            },
        ),
    ]
