# Generated by Django 6.0.6 on 2026-09-24 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=60, unique=True)),
                ('expense_type', models.CharField(choices=[('DAMAGED_GOODS', 'Damaged / Written-Off Goods'), ('OPERATIONAL', 'Operational Expense'), ('LOGISTICS', 'Logistics & Delivery'), ('UTILITY', 'Utility Bill (Light / Water)'), ('STAFF', 'Staff Welfare / Wages'), ('MAINTENANCE', 'Equipment Maintenance'), ('OTHER', 'Other Expense')], default='OPERATIONAL', max_length=30)),
                ('title', models.CharField(help_text="Short description e.g. 'Samsung TV screen cracked during transit'", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('quantity_damaged', models.PositiveIntegerField(default=0, help_text='Qty written off from stock (0 for non-goods expenses)')),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_by', models.CharField(max_length=100)),
                ('recorded_by_role', models.CharField(default='MANAGER', max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.branch')),
                ('product', models.ForeignKey(blank=True, help_text="Link product if it's a damaged goods write-off", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_records', to='inventory.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
